spring:
  datasource:
    data: classpath:init.sql
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console 
  devtools:
    livereload:
      enabled: true 
#security:
#  basic:
#    enabled: false # security 기본 인증 옵션 제거
logging:
  level:
    org.hibernate.type: trace  # JPA로 생성되는 쿼리의 파라미터 값 확인